#!/bin/bash
current_user=$(whoami)
p=$(dirname $(dirname $PWD))
if [ $current_user != "root" ]; then
    echo "$(basename "$0") setup requires superuser privileges to run !"
    exit 1
fi

ping -c 1 www.google.com
if [[ $? -ne 0 ]]; then
    echo "$(basename "$0") setup script requires a network connection to run !"
    exit 1
fi

# get get up to the newest state
apt-get update && apt-get -y upgrade

# maintenance 
#apt-get -y install aptitude
#apt-get -y install bmon
#apt-get -y install htop


# archives 
apt-get -y install unzip

# Julia 
apt-get -y install julia

# rlwrap (for q)
apt-get -y install rlwrap

# erlang
apt-get -y install erlang-base

# rebar
git clone https://github.com/erlang/rebar3.git
cd rebar3 && ./bootstrap

# auto-starts
cp $p/resources/scripts/hydroza_autostart /etc/init.d/
chmod +x /etc/init.d/hydroza_autostart

# kdb+ setup
echo "alias q='QHOME=~/q rlwrap -r ~/q/l32arm/q'" >> ~/.bashrc
cd $p/resources/archives/kdb
unzip kdb_arm.zip
rm q/trade.q q/sp.q q/q.q
cp -r q ~/.
cd -


# clean up
rm -f $p/README.md 
rm -f -r $p/resources
apt-get -y autoremove 
apt-get -y autoclean