#!/bin/bash

current_user=$(whoami)
p=$(dirname $(dirname $(dirname $PWD)))
if [ $current_user != "root" ]; then
    echo "$(basename "$0") setup requires superuser privileges to run !"
    exit 1
fi

ping -c 1 www.google.com
if [[ $? -ne 0 ]]; then
    echo "$(basename "$0") setup script requires a network connection to run !"
    exit 1
fi

# dependencies 
deb http://packages.erlang-solutions.com/debian wheezy contrib
wget http://packages.erlang-solutions.com/debian/erlang_solutions.asc
apt-key add erlang_solutions.asc && rm erlang_solutions.asc

# get get up to the newest state
apt-get update
apt-get -y upgrade

# maintenance 
#apt-get -y install aptitude
#apt-get -y install bmon
#apt-get -y install htop


# development 
apt-get -y install julia
apt-get -y install erlang-mini

# auto-starts
cp $p/resources/scripts/hydroza_autostart /etc/init.d/
chmod +x /etc/init.d/hydroza_autostart

# kdb+ setup
echo "alias q='QHOME=~/q rlwrap -r ~/q/l32/q'" >> ~/.bashrc
cd $p/resources/archives/kdb
unzip kdb_arm.zip
rm q/trade.q 
rm q/sp.q
rm q/q.q
cp -r q ~/.
cd -


# clean up
rm -f $p/README.md 
rm -f -r $p/resources
apt-get -y autoremove 
apt-get -y autoclean